development:
  adapter: mysql
  database: 
  username: 
  password: 
  host: localhost

test:
  adapter: mysql
  database: 
  username: 
  password: 
  host: localhost

production:
  adapter: mysql
  database: 
  username: 
  password: 
  host: 

